### PR TITLE
(chore): release Docker image as part of release

### LINKED ISSUE #317: Feature Request: Release a docker image including runme at docker hub
Hey do you plan to publish an official runme docker image? I am just using runme to test our readme and automated it in a Dockerfile. This works like a charm. Installing runme from GitHub was straight forward but having a image I could download the binary from would be even better.

```
FROM ubuntu:22.04

# Dependencies
RUN apt-get update && apt-get install -y curl bash

ARG BUILDARCH

# Install runme
RUN curl -sSL https://download.stateful.com/runme/1.2.6/runme_linux_${BUILDARCH}.tar.gz  | tar -xz -C /usr/local/bin runme
RUN runme --version
```

### PR DESCRIPTION
**Pull request by christian-bromann**
fixes #317

Added `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` to the repo secrets.

### CODE REVIEW

**Comment by sourishkrout** [comment]
@mxsdev, please review.

**Review by mxsdev — APPROVED** [review]
Tested with `goreleaser`'s local preview release feature, seemed to work alright - code looks correct as well. We'll have to keep an eye out on release just to be sure.

**Comment by sourishkrout** [comment]
What happens if we try building a Release Candidate (which will skip hombrew tap distribution)?

**Comment by christian-bromann** [comment]
@sourishkrout I have `skip_push: auto` set which says:

> # If set to auto, the release will not be pushed to the Docker repository
> #  in case there is an indicator of a prerelease in the tag, e.g. v1.0.0-rc1.

For Homebrew we have this in place:

```yml
        # skip prereleases
        if: ${{ !contains(github.ref, '-') }}
```

**Review by sourishkrout — APPROVED** [review]
👍 Let's merge and do an RC.

**Pull request merged**
