### PR TITLE
Opt to use node-grpc client for codegen

### PR DESCRIPTION
**Pull request by sourishkrout**
This will generate types and implementation code that are compliant with `node-grpc`.

Chose not to commit the generated code yet. I will let you do that post merge, @adambabik.

### CODE REVIEW

**Comment by sourishkrout** [comment]
As per convo/thread on Slack: this is no longer required @adambabik. Feel free to close unmerged.

**Comment by sourishkrout** [comment]
> As per convo/thread on Slack: this is no longer required @adambabik. Feel free to close unmerged.

Actually we might want to commit it anyways. It's handy to do local codegen. Changed the opts to be in line with Buf's registry.

**Comment by adambabik** [comment]
@sourishkrout just to confirm, the default options from the Buf Remote Plugins do work for our case, is that correct?

**Comment by sourishkrout** [comment]
> @sourishkrout just to confirm, the default options from the Buf Remote Plugins do work for our case, is that correct?

Yep, I took them from the generated files distributed through their registry's headers, e.g.:

```js
/* eslint-disable */
// @generated by protobuf-ts 2.8.2 with parameter output_javascript,optimize_code_size,long_type_string,add_pb_suffix,ts_nocheck,eslint_disable
// @generated from protobuf file "runme/parser/v1/parser.proto" (package "runme.parser.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
```

**Pull request merged**
