### PR TITLE
command: fix signalling to command process group

### PR DESCRIPTION
**Pull request by adambabik**
This change also fixes a regression that broken running interactive commands, like runme in runme, run from the CLI in https://github.com/stateful/runme/pull/637/commits/da2c38c928edec6858b1833bcfb3e2db638d2090.

It also disables FIFO which should mitigate https://github.com/stateful/runme/issues/635 but a proper fix is needed.

Relates to https://github.com/stateful/runme/issues/636

### CODE REVIEW

**Comment by adambabik** [comment]
@sourishkrout I was able to reproduce the issue and verify this fix using grpcurl.

**Comment by adambabik** [comment]
@sourishkrout there is a genuine problem with `TestRunnerServiceServerExecute_WithStop` so getting this PR back to draft.

I dug into this and when doing CTRL-C in the terminal, you actually send a SIGINT to the whole process group ([a great thread](https://superuser.com/a/1830133) that explains it thoroughly). Now I remember why I implemented this :) However, when running a server and executing commands by it, the server and the commands share the same process group and we kill the server when we send a signal to the process group; the effect is the reported bug.

It seems like the ideal solution is to make the command its own process group, just as it is done by bash. I will try that. In fact, there is code doing that but it's not used in v2.

**Comment by sourishkrout** [comment]
> I dug into this and when doing CTRL-C in the terminal, you actually send a SIGINT to the whole process group ([a great thread](https://superuser.com/a/1830133) that explains it thoroughly). Now I remember why I implemented this :) However, when running a server and executing commands by it, the server and the commands share the same process group and we kill the server when we send a signal to the process group; the effect is the reported bug.

That explains why the kernel server suddenly dies 😆.

**Comment by adambabik** [comment]
@sourishkrout ready to test and review.

**Review by sourishkrout — APPROVED** [review]
👍 LGTM

**Pull request merged**
