### PR TITLE
allow copying from tui with "y" or "c"

### PR DESCRIPTION
**Pull request by mxsdev**
Use "y" or "c" to copy command contents to clipboard.

Maybe we should escape new lines with `\`?

### CODE REVIEW

**Review by mikeage — APPROVED** [review]
thanks! Perfect :-)

**Comment by mikeage** [comment]
hi, is it possible to merge this? :-)

**Comment by mxsdev** [comment]
@mikeage Hey, before merging I'd probably want to add it to the command list. But the command list is getting kinda large, so I probably would want to hide it behind a "show more" button

@sourishkrout thoughts on having a "silent command" that's not listed? Is that alright or poor UX in your mind?

**Comment by sourishkrout** [comment]
> @mikeage Hey, before merging I'd probably want to add it to the command list. But the command list is getting kinda large, so I probably would want to hide it behind a "show more" button/menu
> 
> @sourishkrout thoughts on having a "silent command" that's not listed? Is that alright or poor UX in your mind?

looking at this now. we can probably turn this around fast.

**Comment by sourishkrout** [comment]
@mxsdev, how about we ship this as is and create a follow-up ticket for the UX?

I've seen bubbletea TUI's having an intermediate "help" screen that shows all the shortcuts to not overflow the bottom line.

**Comment by mxsdev** [comment]
See #204

**Comment by sourishkrout** [comment]
@mikeage we shipped `runme` v1 with these shortcuts. If you're on homebrew, it should be a matter of running upgrade. Have fun, and let us know if there's anything else you need.

**Pull request merged**
