### PR TITLE
Add internal/project

### PR DESCRIPTION
**Pull request by adambabik**
This PR adds a refactored implementation of `pkg/project` in `internal/project`. For now, it's unused. Further adjustments will be added, when the usage of `internal/project` is incorporated in the rest of the program.

### CODE REVIEW

**Comment by sourishkrout** [comment]
Great @adambabik! Should we review it now or once it's integrated?

**Comment by adambabik** [comment]
@sourishkrout let's do it now so that the PR is not massive. I will create a projects gRPC service based on it first, and when it's accepted, I will integrate "internal/project" into other parts of the program.

**Comment by adambabik** [comment]
@sourishkrout After giving it a bit more thought, I think it might be hard to review from the functional point of view. Let's do it when the gRPC service is implemented.

**Comment by sourishkrout** [comment]
> @sourishkrout After giving it a bit more thought, I think it might be hard to review from the functional point of view. Let's do it when the gRPC service is implemented.

Aye aye, sir!

**Comment by adambabik** [comment]
Replaced with https://github.com/stateful/runme/pull/438

**Pull request closed without merging**
