### PR TITLE
Only use timostamm-protobuf-ts

### PR DESCRIPTION
**Pull request by sourishkrout**
Removes odd side-effect of directly relying on the generate files in TS/JS. We are using `timostamm-protobuf-ts` which is mostly important on the client-side to get full Typescript benefits.

(cc @pastuxso)

Fixes https://github.com/stateful/runme/issues/305.

### CODE REVIEW

**Comment by sourishkrout** [comment]
I'm also wondering if we should remove buf connect, @adambabik, since we aren't actually using it to connect to the kernel APIs.

**Comment by adambabik** [comment]
@sourishkrout yeah, it was an experiment. If we use gRPC exclusively, we can totally get rid of connect. There is a plugin to remove and some code from `server.go`.

**Comment by sourishkrout** [comment]
Can I get an approval, please, @pastuxso? Thank you.

**Review by pastuxso — APPROVED** [review]
LGTM

**Pull request merged**
