### PR TITLE
Add skipPrompts frontmatter option

### PR DESCRIPTION
**Pull request by degrammer**
Add new FrontMatter option: **skipPrompts**, a boolean value that can be used at the document level to skip environment prompts:

```
---
skipPrompts: true
---
```

### CODE REVIEW

**Review by duvanmonsa — APPROVED** [review]

**Comment by sourishkrout** [comment]
FYI, @degrammer & @duvanmonsa, I'd like to do a review myself prior to merging protobuf/gRPC changes.

**Review by sourishkrout — CHANGES_REQUESTED** [review]
No example in https://github.com/stateful/runme/tree/main/examples/frontmatter.

**Review by sourishkrout — CHANGES_REQUESTED** [review]
Let's rename it to `skipPrompts` as per the CLI. It's about prompts, not envs and consistency is important. Also why is all lowercase? Wouldn't a YAML/JSON encoding be `skipEnv` or after renaming it `skipPrompts`?

```
❯ ./runme run --help
Run a selected command identified based on its unique parsed name.

Usage:
  runme run <commands> [flags]
[...]
      --skip-prompts            Skip prompting for variables.
[...]
```

**Review by sourishkrout — APPROVED** [review]
LGTM 👍.

**Pull request merged**
